package com.gtnewhorizons.angelica.transform;

import it.unimi.dsi.fastutil.objects.ObjectOpenHashSet;

public class LegacyGLCalls {
    static final ObjectOpenHashSet<String> illegalCalls = new ObjectOpenHashSet<>(new String[]{
            "glPushMatrix ()V",
            "glColor4f (FFFF)V",
            "glMatrixMode (I)V",
            "glTranslatef (FFF)V",
            "glRotatef (FFFF)V",
            "glClientActiveTexture (I)V",
            "glMultiTexCoord2f (IFF)V",
            "glGenLists (I)I",
            "glDeleteLists (II)V",
            "glMultMatrix (Ljava/nio/FloatBuffer;)V",
            "glBegin (I)V",
            "glTexCoord2f (FF)V",
            "glFog (ILjava/nio/FloatBuffer;)V",
            "glFogf (IF)V",
            "glTexCoordPointer (IILjava/nio/FloatBuffer;)V",
            "glFogi (II)V",
            "glPushAttrib (I)V",
            "glAlphaFunc (IF)V",
            "glScalef (FFF)V",
            "glColor3f (FFF)V",
            "glTranslated (DDD)V",
            "glPopMatrix ()V",
            "glNewList (II)V",
            "glPopAttrib ()V",
            "glColor4d (DDDD)V",
            "glScaled (DDD)V",
            "glVertex3d (DDD)V",
            "glMultMatrix (Ljava/nio/DoubleBuffer;)V",
            "glPushClientAttrib (I)V",
            "glNormal3f (FFF)V",
            "glShadeModel (I)V",
            "glColor4ub (BBBB)V",
            "glDisableClientState (I)V",
            "glColorPointer (IIIJ)V",
            "glNormalPointer (IIJ)V",
            "glVertexPointer (IIIJ)V",
            "glEnd ()V",
            "glColor3ub (BBB)V",
            "glColor4b (BBBB)V",
            "glTexCoord2d (DD)V",
            "glColor3d (DDD)V",
            "glCallList (I)V",
            "glClipPlane (ILjava/nio/DoubleBuffer;)V",
            "glLoadMatrix (Ljava/nio/FloatBuffer;)V",
            "glScissor (IIII)V",
            "glLoadIdentity ()V",
            "glOrtho (DDDDDD)V",
    });
}
